services:
  bun:
    build: ./client/
    volumes:
      - static:/app/static

  server:
    build: ./
    ports:
      - 8080:6969
    volumes:
      - static:/app/static
    environment:
      MODEL_URL: "http://model:8000"

  model:
    build: ./model/

volumes:
  static:
